apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: javacheck-backend-postgres-password
  namespace: storefront-dev222
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: teams-dev/storefront-dev222/POSTGRES_PASSWORD
