apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: javacheck-backend-google-client-secret
  namespace: storefront-dev222
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: teams-dev/storefront-dev222/GOOGLE_CLIENT_SECRET
